server:
  servlet:
    context-path: /server
  port: 8090
spring:
  redis:
    host: localhost
    port: 6379
    password:
    database: 12

mqtt-properties:
  # MQTT-服务器连接地址，如果有多个，用逗号隔开，如：tcp://127.0.0.1:61613，tcp://192.168.2.133:61613
  host: tcp://localhost:1883
  # MQTT-连接服务器默认客户端ID
  clientId: Server
  # 用户名
  username: admin
  # 密码
  password: admin

  cleanSession: false
  connectionTimeout: 300
  # 设置会话心跳时间
  keepAliveInterval: 60
  # 此属性设置为true的话，连接断开会自动重连
  automaticReconnect: true
  defaultQos: 0
