server:
  servlet:
    context-path: /server
  port: 8091
spring:
  redis:
    host: localhost
    port: 6379
    password:
    database: 12

mqtt-properties:
  host: tcp://localhost:1883
  clientId: Server
  username: admin
  password: admin
  cleanSession: false
  connectionTimeout: 300
  keepAliveInterval: 60
  automaticReconnect: true
  defaultQos: 0
